# Generated by Django 6.0.7 on 2026-08-05 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('visit_time', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bhk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.bhktype')),
            ],
        ),
    ]
